vti_encoding:SR|utf8-nl
vti_cachedlinkinfo:VX|A|chat01.asp
vti_timecreated:TR|17 Sep 2002 03:25:01 +0200
vti_cacheddtm:TX|28 Sep 2002 02:05:34 +0200
vti_timelastmodified:TR|17 Sep 2002 03:54:23 +0200
vti_cachedhasbots:BR|false
vti_filesize:IX|940
vti_extenderversion:SR|3.0.2.926
vti_backlinkinfo:VX|chat01.asp
vti_cachedhasborder:BR|false
vti_author:SR|anigno
vti_cachedhastheme:BR|false
vti_cachedbodystyle:SR|<body>
vti_nexttolasttimemodified:TR|17 Sep 2002 03:54:23 +0200
vti_modifiedby:SR|anigno
