vti_encoding:SR|utf8-nl
vti_author:SR|anigno
vti_cachedlinkinfo:VX|A|chat02.asp
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_timecreated:TR|17 Sep 2002 03:25:01 +0200
vti_filesize:IX|664
vti_cachedbodystyle:SR|<body>
vti_modifiedby:SR|anigno
vti_backlinkinfo:VX|index.htm chat.htm chat02.asp
vti_cacheddtm:TX|17 Sep 2002 04:02:18 +0200
vti_cachedhasbots:BR|false
vti_nexttolasttimemodified:TR|17 Sep 2002 03:54:23 +0200
vti_extenderversion:SR|3.0.2.926
vti_timelastmodified:TR|17 Sep 2002 03:54:23 +0200
