<%@ Language=VBScript %>
<HTML>
<HEAD>
<meta NAME="GENERATOR" Content="Microsoft FrontPage 5.0">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1255">
<meta name="ms.locale" content="HE"></HEAD>
<BODY>
	<%=Application("line01")%><BR>
	<%=Application("line02")%><BR>
	<%=Application("line03")%><BR>
	<%=Application("line04")%><BR>
	<%=Application("line05")%><BR>
	<%=Application("line06")%><BR>
	<%=Application("line07")%><BR>
	<%=Application("line08")%><BR>
	<%=Application("line09")%><BR>
	<%=Application("line10")%><BR>
<script language=vbscript>
setTimeout "runReload",2000
sub runReload()
	window.location.reload	
end sub

</script>
</BODY>
</HTML>
