<%@ Language=VBScript %>
<HTML>
<HEAD>
<META NAME="GENERATOR" Content="Microsoft Visual Studio 6.0">
</HEAD>
<BODY>

<P>&nbsp;</P>
<form name="get1" action="get2.asp" method="get">
	<P>&nbsp;</P>
	<P>first name<INPUT id=text1 name=fName></P>
	<P>last name&nbsp;<INPUT id=text2 name=lName></P>
	<P><INPUT id=submit1 name=submit1 type=submit value=Submit>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
	<INPUT id=reset1 name=reset1 type=reset value=Reset></P>
</form>

</BODY>
</HTML>
