<%@ Language=VBScript %>
<HTML>
<HEAD>
<META NAME="GENERATOR" Content="Microsoft Visual Studio 6.0">
</HEAD>
<BODY>
<form action=post01request.asp name=post01 method=post><BR>

	name<INPUT id=text1 name=txtName> <BR>
	phone<INPUT id=text2 name=txtPhone> 
<BR>
	<INPUT id=submit1 name=submit1 type=submit value=Submit> <BR>
	<INPUT id=reset1 name=reset1 type=reset value=Reset><BR><BR><BR><BR><BR><BR>
	
	
	
	
	
	

</form>



<P>&nbsp;</P>
</BODY>
</HTML>
