<%@ Language=VBScript %>
<html>
<head>
<meta NAME="GENERATOR" Content="Microsoft FrontPage 5.0">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1255">
<meta name="ms.locale" content="HE">

<base target="_self">
</head>
<body bgcolor="#fefff6" text="#ff6600" link="#ff3300" vlink="#ff3300" alink="#ff3300" bgproperties="fixed">
<table>
<tr><td></td></tr>
<tr><td><img src="images/batterfly01.jpg" style="HEIGHT: 415px; WIDTH: 141px" WIDTH="141" HEIGHT="151"></td></tr>
<tr><td></td></tr>
</table>
</body>
</html>