vti_encoding:SR|utf8-nl
vti_author:SR|anigno
vti_cachedlinkinfo:VX|Y|../data.htm S|../../bg01.jpg
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_timecreated:TR|01 Dec 2002 04:04:01 +0200
vti_filesize:IX|547
vti_error0:SX|The page settings references a "Get Background and Colors from Page" URL of "../data.htm", but the file for this URL cannot be found.
vti_cachedbodystyle:SR|<body dir="rtl" stylesrc="../data.htm" background="../../bg01.jpg" text="#440000" link="#800000" vlink="#800000" alink="#CC0000" rightmargin="0" bottommargin="0" leftmargin="0" topMargin="0">
vti_modifiedby:SR|anigno
vti_backlinkinfo:VX|index.htm
vti_cacheddtm:TX|01 Dec 2002 04:21:26 +0200
vti_cachedhasbots:BR|false
vti_nexttolasttimemodified:TR|01 Dec 2002 04:21:26 +0200
vti_extenderversion:SR|3.0.2.926
vti_timelastmodified:TR|01 Dec 2002 04:21:26 +0200
