vti_encoding:SR|utf8-nl
vti_cachedlinkinfo:VX|A|ipfinder.asp
vti_timecreated:TR|17 Oct 2002 01:51:44 +0200
vti_cacheddtm:TX|18 Oct 2002 11:20:24 +0200
vti_timelastmodified:TR|18 Oct 2002 11:14:37 +0200
vti_cachedhasbots:BR|false
vti_filesize:IX|2146
vti_extenderversion:SR|3.0.2.926
vti_backlinkinfo:VX|ipfinder.asp
vti_cachedhasborder:BR|false
vti_author:SR|anigno
vti_cachedhastheme:BR|false
vti_cachedbodystyle:SR|<body>
vti_nexttolasttimemodified:TR|18 Oct 2002 11:14:37 +0200
vti_modifiedby:SR|anigno
