<%@ Language=VBScript %>
<html>
<head>
<meta NAME="GENERATOR" Content="Microsoft FrontPage 5.0">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1255">
<meta name="ms.locale" content="HE">
</head>
<frameset cols="*,250">
	<frameset rows="90,*">
		<frame src="header.asp" scrolling="no" name="frameHeader" noresize>
		<frame src="data.asp" name="frameData">
	</frameset>
	<frameset rows="*,20%">
		<frame src="friends.asp" name="frameFriends">
		<frame src="service.asp">
	</frameset>
</frameset>
</html>