<HTML>
<HEAD>
<meta NAME="GENERATOR" Content="Microsoft FrontPage 5.0">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1255">
<meta name="ms.locale" content="HE">
<TITLE></TITLE>
</HEAD>
<frameset rows="*,153">
<frame src="recieve.asp?Friend=<%=Request.QueryString("Friend")%>" scrolling="auto" name="frameCall" noresize>
<frame src="send.asp?Friend=<%=Request.QueryString("Friend")%>" scrolling="no" name="frameSend" noresize>
</frameset>
</HTML>
