vti_encoding:SR|utf8-nl
vti_author:SR|anigno
vti_cachedlinkinfo:VX|H|main.asp H|main.asp A|update.asp
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_timecreated:TR|13 May 2002 08:57:18 +0200
vti_filesize:IX|2204
vti_cachedbodystyle:SR|<body>
vti_modifiedby:SR|anigno
vti_backlinkinfo:VX|index.asp main.asp
vti_cacheddtm:TX|13 May 2002 18:02:00 +0200
vti_cachedhasbots:BR|false
vti_nexttolasttimemodified:TR|13 May 2002 18:02:00 +0200
vti_extenderversion:SR|3.0.2.926
vti_timelastmodified:TR|13 May 2002 18:02:00 +0200
