<%@ Language=VBScript %>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1255">
<meta name="ms.locale" content="HE">


<body dir="rtl" background="../../bg01.jpg" text="#440000" link="#800000" vlink="#800000" alink="#cc0000" stylesrc="../data.htm">

<table>
<tr><td><a href="search.asp">חיפוש מודעה</a></td></tr>
<tr><td><a href="addNew.asp">הוספת מודעה</a></td></tr></table>
<table></table>
<p>&nbsp;</p>
<p>בבקשה לא לשלוח את אותה מודעה מספר פעמים!</p>

	
 
	
</body>
</html>
