<%@ Page language="c#" Codebehind="fRegistration.aspx.cs" AutoEventWireup="false" Inherits="nifgashim30.registration.fRegistration" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" >
<HTML dir="ltr">
	<HEAD>
		<title>fRegistration</title>
		<meta content="Microsoft Visual Studio .NET 7.1" name="GENERATOR">
		<meta content="C#" name="CODE_LANGUAGE">
		<meta content="JavaScript" name="vs_defaultClientScript">
		<meta content="http://schemas.microsoft.com/intellisense/ie5" name="vs_targetSchema">
	</HEAD>
	<body MS_POSITIONING="GridLayout">
		<form id="Form1" method="post" runat="server">
			<asp:dropdownlist id="drpSex" style="Z-INDEX: 101; LEFT: 560px; POSITION: absolute; TOP: 248px" tabIndex="5"
				runat="server" Width="56px"></asp:dropdownlist>
			<asp:Button id="Button1" style="Z-INDEX: 197; LEFT: 744px; POSITION: absolute; TOP: 24px" runat="server"
				Text="Button" CausesValidation="False"></asp:Button>
			<asp:Button id="btnDummy" style="Z-INDEX: 196; LEFT: 24px; POSITION: absolute; TOP: 920px" runat="server"
				Width="16px" Text="dummy" Height="12px"></asp:Button>
			<asp:Button id="btnMainPage" style="Z-INDEX: 195; LEFT: 392px; POSITION: absolute; TOP: 912px"
				runat="server" Width="112px" Text="חזרה" CausesValidation="False"></asp:Button><asp:label id="Label15" style="Z-INDEX: 171; LEFT: 320px; POSITION: absolute; TOP: 8px" runat="server"
				Font-Underline="True">ספר לנו מי אתה</asp:label><asp:label id="lblMessage" style="Z-INDEX: 170; LEFT: 512px; POSITION: absolute; TOP: 40px"
				runat="server" Width="112px" Visible="False" ForeColor="Red" Font-Size="Smaller">שם משתמש תפוס</asp:label><asp:regularexpressionvalidator id="RegularExpressionValidator7" style="Z-INDEX: 169; LEFT: 40px; POSITION: absolute; TOP: 328px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[ א-תףןצםa-zA-Z0-9]{1,}" ErrorMessage="!אותיות עבריות ולועזיות, רווחים ומספרים" ControlToValidate="txtWork"></asp:regularexpressionvalidator><asp:regularexpressionvalidator id="RegularExpressionValidator6" style="Z-INDEX: 168; LEFT: 40px; POSITION: absolute; TOP: 280px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[ א-תףןצםa-zA-Z0-9]{1,}" ErrorMessage="!אותיות עבריות ולועזיות, רווחים ומספרים" ControlToValidate="txtStudy"></asp:regularexpressionvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator3" style="Z-INDEX: 167; LEFT: 24px; POSITION: absolute; TOP: 304px"
				runat="server" ErrorMessage="?" ControlToValidate="txtStudy"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator2" style="Z-INDEX: 164; LEFT: 24px; POSITION: absolute; TOP: 344px"
				runat="server" ErrorMessage="?" ControlToValidate="txtWork"></asp:requiredfieldvalidator><asp:label id="Label18" style="Z-INDEX: 145; LEFT: 248px; POSITION: absolute; TOP: 376px" runat="server">מצב כלכלי</asp:label><asp:dropdownlist id="drpAconomicState" style="Z-INDEX: 143; LEFT: 40px; POSITION: absolute; TOP: 376px"
				tabIndex="26" runat="server" Width="194px"></asp:dropdownlist><asp:label id="Label17" style="Z-INDEX: 141; LEFT: 248px; POSITION: absolute; TOP: 344px" runat="server">תחום עיסוק</asp:label><asp:textbox id="txtWork" style="Z-INDEX: 139; LEFT: 40px; POSITION: absolute; TOP: 344px" tabIndex="25"
				runat="server" Width="192px"></asp:textbox><asp:label id="Label16" style="Z-INDEX: 136; LEFT: 240px; POSITION: absolute; TOP: 296px" runat="server">תחום לימודים</asp:label><asp:textbox id="txtStudy" style="Z-INDEX: 134; LEFT: 40px; POSITION: absolute; TOP: 296px" tabIndex="24"
				runat="server" Width="192px"></asp:textbox><asp:label id="Label14" style="Z-INDEX: 133; LEFT: 248px; POSITION: absolute; TOP: 256px" runat="server">השכלה</asp:label><asp:dropdownlist id="drpEducation" style="Z-INDEX: 130; LEFT: 48px; POSITION: absolute; TOP: 256px"
				tabIndex="23" runat="server" Width="186px"></asp:dropdownlist><asp:regularexpressionvalidator id="RegularExpressionValidator5" style="Z-INDEX: 166; LEFT: 432px; POSITION: absolute; TOP: 496px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[ א-תףןצםa-zA-Z0-9]{1,}" ErrorMessage="!אותיות עבריות ולועזיות, רווחים ומספרים" ControlToValidate="txtSelfDescription"></asp:regularexpressionvalidator><asp:regularexpressionvalidator id="RegularExpressionValidator4" style="Z-INDEX: 165; LEFT: 512px; POSITION: absolute; TOP: 376px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[א-תףןםץ ]{1,}" ErrorMessage="!אותיות עבריות ורווחים" ControlToValidate="txtCity"></asp:regularexpressionvalidator><asp:regularexpressionvalidator id="RegularExpressionValidator3" style="Z-INDEX: 163; LEFT: 504px; POSITION: absolute; TOP: 224px"
				runat="server" Font-Size="XX-Small" ValidationExpression="\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" ErrorMessage='!כתובת דוא"ל לא חוקית' ControlToValidate="txtEmail"></asp:regularexpressionvalidator><asp:comparevalidator id="CompareValidator1" style="Z-INDEX: 162; LEFT: 528px; POSITION: absolute; TOP: 184px"
				runat="server" Font-Size="XX-Small" ErrorMessage="!סיסמאות לא זהות" ControlToValidate="txtPassword2" ControlToCompare="txtPassword1"></asp:comparevalidator><asp:regularexpressionvalidator id="RegularExpressionValidator2" style="Z-INDEX: 161; LEFT: 368px; POSITION: absolute; TOP: 56px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[_a-zA-z0-9]{4,}" ErrorMessage="!אותיות לועזיות, ספרות וקו תחתון באורך של 4 לפחות" ControlToValidate="txtUserName"></asp:regularexpressionvalidator><asp:regularexpressionvalidator id="RegularExpressionValidator1" style="Z-INDEX: 160; LEFT: 368px; POSITION: absolute; TOP: 104px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[_a-zA-z0-9]{4,}" ErrorMessage="!אותיות לועזיות, ספרות וקו תחתון באורך של 4 לפחות" ControlToValidate="txtPassword1"></asp:regularexpressionvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator9" style="Z-INDEX: 159; LEFT: 624px; POSITION: absolute; TOP: 472px"
				runat="server" ErrorMessage="?" ControlToValidate="txtSelfDescription"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator7" style="Z-INDEX: 158; LEFT: 400px; POSITION: absolute; TOP: 72px"
				runat="server" ErrorMessage="?" ControlToValidate="txtUserName"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator6" style="Z-INDEX: 157; LEFT: 400px; POSITION: absolute; TOP: 120px"
				runat="server" ErrorMessage="?" ControlToValidate="txtPassword1"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator5" style="Z-INDEX: 156; LEFT: 400px; POSITION: absolute; TOP: 152px"
				runat="server" ErrorMessage="?" ControlToValidate="txtPassword2"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator4" style="Z-INDEX: 155; LEFT: 400px; POSITION: absolute; TOP: 200px"
				runat="server" ErrorMessage="?" ControlToValidate="txtEmail"></asp:requiredfieldvalidator><asp:requiredfieldvalidator id="RequiredFieldValidator1" style="Z-INDEX: 154; LEFT: 408px; POSITION: absolute; TOP: 392px"
				runat="server" ErrorMessage="?" ControlToValidate="txtCity"></asp:requiredfieldvalidator><asp:label id="Label20" style="Z-INDEX: 152; LEFT: 632px; POSITION: absolute; TOP: 424px" runat="server">תאור עצמי</asp:label><asp:textbox id="txtSelfDescription" style="Z-INDEX: 102; LEFT: 48px; POSITION: absolute; TOP: 424px"
				tabIndex="27" runat="server" Width="573px" Height="72px" TextMode="MultiLine"></asp:textbox><asp:dropdownlist id="drpSport" style="Z-INDEX: 151; LEFT: 48px; POSITION: absolute; TOP: 192px" tabIndex="20"
				runat="server" Width="240px"></asp:dropdownlist><asp:label id="Label26" style="Z-INDEX: 150; LEFT: 296px; POSITION: absolute; TOP: 192px" runat="server">פעילות גופנית</asp:label><asp:dropdownlist id="drpOrigin" style="Z-INDEX: 149; LEFT: 48px; POSITION: absolute; TOP: 128px"
				tabIndex="18" runat="server" Width="65px"></asp:dropdownlist><asp:label id="Label25" style="Z-INDEX: 148; LEFT: 120px; POSITION: absolute; TOP: 128px" runat="server">מוצא</asp:label><asp:label id="Label24" style="Z-INDEX: 147; LEFT: 120px; POSITION: absolute; TOP: 96px" runat="server">מזל</asp:label><asp:dropdownlist id="drpLuck" style="Z-INDEX: 146; LEFT: 48px; POSITION: absolute; TOP: 96px" tabIndex="16"
				runat="server" Width="65px"></asp:dropdownlist><asp:label id="Label23" style="Z-INDEX: 144; LEFT: 208px; POSITION: absolute; TOP: 160px" runat="server">נכונות לשנות מקום מגורים</asp:label><asp:dropdownlist id="drpChangeHome" style="Z-INDEX: 142; LEFT: 48px; POSITION: absolute; TOP: 160px"
				tabIndex="19" runat="server" Width="152px"></asp:dropdownlist><asp:dropdownlist id="drpBody" style="Z-INDEX: 140; LEFT: 160px; POSITION: absolute; TOP: 96px" tabIndex="15"
				runat="server" Width="120px"></asp:dropdownlist><asp:label id="Label22" style="Z-INDEX: 138; LEFT: 296px; POSITION: absolute; TOP: 96px" runat="server">מבנה גוף</asp:label><asp:label id="Label21" style="Z-INDEX: 137; LEFT: 120px; POSITION: absolute; TOP: 64px" runat="server">גובה</asp:label><asp:dropdownlist id="drpHeight" style="Z-INDEX: 135; LEFT: 48px; POSITION: absolute; TOP: 64px" tabIndex="14"
				runat="server" Width="65px"></asp:dropdownlist><asp:dropdownlist id="drpSmoke" style="Z-INDEX: 132; LEFT: 160px; POSITION: absolute; TOP: 64px" tabIndex="13"
				runat="server" Width="120px"></asp:dropdownlist><asp:label id="Label19" style="Z-INDEX: 131; LEFT: 296px; POSITION: absolute; TOP: 64px" runat="server">עישון</asp:label><asp:label id="Label13" style="Z-INDEX: 129; LEFT: 176px; POSITION: absolute; TOP: 224px" runat="server">ילדים</asp:label><asp:dropdownlist id="drpChildren" style="Z-INDEX: 128; LEFT: 48px; POSITION: absolute; TOP: 224px"
				tabIndex="22" runat="server" Width="120px"></asp:dropdownlist><asp:label id="Label12" style="Z-INDEX: 127; LEFT: 296px; POSITION: absolute; TOP: 224px" runat="server">מצב משפחתי</asp:label><asp:dropdownlist id="drpFamilyState" style="Z-INDEX: 124; LEFT: 224px; POSITION: absolute; TOP: 224px"
				tabIndex="21" runat="server" Width="65px"></asp:dropdownlist><asp:label id="Label11" style="Z-INDEX: 126; LEFT: 296px; POSITION: absolute; TOP: 128px" runat="server">זיקה לדת</asp:label><asp:dropdownlist id="drpReligion" style="Z-INDEX: 125; LEFT: 160px; POSITION: absolute; TOP: 128px"
				tabIndex="17" runat="server" Width="120px"></asp:dropdownlist><asp:label id="Label10" style="Z-INDEX: 123; LEFT: 624px; POSITION: absolute; TOP: 392px" runat="server">עיר</asp:label><asp:textbox id="txtCity" style="Z-INDEX: 122; LEFT: 424px; POSITION: absolute; TOP: 392px" tabIndex="12"
				runat="server" Width="192px"></asp:textbox><asp:label id="Label9" style="Z-INDEX: 121; LEFT: 624px; POSITION: absolute; TOP: 280px" runat="server">מטרת הכרות</asp:label><asp:dropdownlist id="drpRelationshipCause" style="Z-INDEX: 120; LEFT: 424px; POSITION: absolute; TOP: 280px"
				tabIndex="7" runat="server" Width="195px"></asp:dropdownlist><asp:label id="Label3" style="Z-INDEX: 119; LEFT: 624px; POSITION: absolute; TOP: 312px" runat="server">תאריך לידה</asp:label><asp:dropdownlist id="drpYear" style="Z-INDEX: 118; LEFT: 552px; POSITION: absolute; TOP: 312px" tabIndex="10"
				runat="server" Width="65px"></asp:dropdownlist><asp:dropdownlist id="drpMonth" style="Z-INDEX: 117; LEFT: 488px; POSITION: absolute; TOP: 312px"
				tabIndex="9" runat="server" Width="57px"></asp:dropdownlist><asp:dropdownlist id="drpDay" style="Z-INDEX: 116; LEFT: 424px; POSITION: absolute; TOP: 312px" tabIndex="8"
				runat="server" Width="56px"></asp:dropdownlist><asp:label id="Label8" style="Z-INDEX: 115; LEFT: 616px; POSITION: absolute; TOP: 200px" runat="server">דואר אלקטרוני</asp:label><asp:label id="Label7" style="Z-INDEX: 114; LEFT: 616px; POSITION: absolute; TOP: 152px" runat="server">אימות סיסמה</asp:label><asp:label id="Label6" style="Z-INDEX: 113; LEFT: 616px; POSITION: absolute; TOP: 120px" runat="server">סיסמה</asp:label><asp:textbox id="txtEmail" style="Z-INDEX: 112; LEFT: 416px; POSITION: absolute; TOP: 200px"
				tabIndex="4" runat="server" Width="195px"></asp:textbox><asp:textbox id="txtPassword2" style="Z-INDEX: 111; LEFT: 416px; POSITION: absolute; TOP: 152px"
				tabIndex="3" runat="server" Width="195px" TextMode="Password"></asp:textbox><asp:textbox id="txtPassword1" style="Z-INDEX: 110; LEFT: 416px; POSITION: absolute; TOP: 120px"
				tabIndex="2" runat="server" Width="195px" TextMode="Password"></asp:textbox><asp:label id="Label5" style="Z-INDEX: 109; LEFT: 624px; POSITION: absolute; TOP: 344px" runat="server">איזור מגורים</asp:label><asp:dropdownlist id="drpRegion" style="Z-INDEX: 108; LEFT: 424px; POSITION: absolute; TOP: 344px"
				tabIndex="11" runat="server" Width="195px"></asp:dropdownlist><asp:label id="Label4" style="Z-INDEX: 107; LEFT: 488px; POSITION: absolute; TOP: 248px" runat="server">מעוניין ב</asp:label><asp:dropdownlist id="drpRequiredSex" style="Z-INDEX: 106; LEFT: 424px; POSITION: absolute; TOP: 248px"
				tabIndex="6" runat="server" Width="56px"></asp:dropdownlist><asp:label id="Label2" style="Z-INDEX: 105; LEFT: 616px; POSITION: absolute; TOP: 72px" runat="server">כינוי</asp:label><asp:textbox id="txtUserName" style="Z-INDEX: 104; LEFT: 416px; POSITION: absolute; TOP: 72px"
				tabIndex="1" runat="server" Width="195px"></asp:textbox><asp:label id="Label1" style="Z-INDEX: 103; LEFT: 624px; POSITION: absolute; TOP: 248px" runat="server">מין</asp:label><asp:button id="btnContinue" style="Z-INDEX: 153; LEFT: 512px; POSITION: absolute; TOP: 912px"
				tabIndex="41" runat="server" Text="שלח לביצוע"></asp:button><asp:label id="Label33" style="Z-INDEX: 172; LEFT: 296px; POSITION: absolute; TOP: 560px" runat="server"
				Font-Underline="True">ספר לנו מה אתה מחפש</asp:label><asp:textbox id="txtOtherPersonDescription" style="Z-INDEX: 173; LEFT: 48px; POSITION: absolute; TOP: 608px"
				tabIndex="28" runat="server" Width="576px" Height="72px" TextMode="MultiLine"></asp:textbox><asp:label id="Label27" style="Z-INDEX: 174; LEFT: 640px; POSITION: absolute; TOP: 608px" runat="server">האדם שברצוני לפגוש</asp:label><asp:dropdownlist id="drpRequestedRegion" style="Z-INDEX: 175; LEFT: 440px; POSITION: absolute; TOP: 696px"
				tabIndex="29" runat="server" Width="184px"></asp:dropdownlist><asp:label id="Label32" style="Z-INDEX: 176; LEFT: 632px; POSITION: absolute; TOP: 696px" runat="server">איזור מגורים</asp:label><asp:regularexpressionvalidator id="RegularExpressionValidator8" style="Z-INDEX: 177; LEFT: 432px; POSITION: absolute; TOP: 592px"
				runat="server" Font-Size="XX-Small" ValidationExpression="[ א-תףןצםa-zA-Z0-9]{1,}" ErrorMessage="!אותיות עבריות ולועזיות, רווחים ומספרים" ControlToValidate="txtOtherPersonDescription"></asp:regularexpressionvalidator><asp:comparevalidator id="CompareValidator2" style="Z-INDEX: 178; LEFT: 376px; POSITION: absolute; TOP: 744px"
				runat="server" Font-Size="XX-Small" ErrorMessage="!טווח גילאים לא לא נכון" ControlToValidate="drpMinAge" ControlToCompare="drpMaxAge" Operator="LessThanEqual" Type="Integer"></asp:comparevalidator><asp:dropdownlist id="drpMinAge" style="Z-INDEX: 179; LEFT: 584px; POSITION: absolute; TOP: 744px"
				tabIndex="30" runat="server" Width="40px"></asp:dropdownlist><asp:dropdownlist id="drpMaxAge" style="Z-INDEX: 180; LEFT: 504px; POSITION: absolute; TOP: 744px"
				tabIndex="31" runat="server" Width="41px"></asp:dropdownlist><asp:label id="Label29" style="Z-INDEX: 181; LEFT: 552px; POSITION: absolute; TOP: 744px" runat="server">עד</asp:label><asp:label id="Label28" style="Z-INDEX: 182; LEFT: 632px; POSITION: absolute; TOP: 744px" runat="server">טווח גילאים</asp:label><asp:label id="Label31" style="Z-INDEX: 183; LEFT: 632px; POSITION: absolute; TOP: 784px" runat="server"
				Width="129px">רמת השכלה רצויה</asp:label><asp:checkbox id="chkHighScholl" style="Z-INDEX: 184; LEFT: 560px; POSITION: absolute; TOP: 784px"
				tabIndex="32" runat="server" Text="תיכון"></asp:checkbox><asp:checkbox id="chkSomeDegree" style="Z-INDEX: 185; LEFT: 384px; POSITION: absolute; TOP: 784px"
				tabIndex="33" runat="server" Text="לימודי תעודה"></asp:checkbox><asp:checkbox id="chkFirstDegree" style="Z-INDEX: 186; LEFT: 512px; POSITION: absolute; TOP: 808px"
				tabIndex="34" runat="server" Text="תואר ראשון"></asp:checkbox><asp:checkbox id="chkSecondDegree" style="Z-INDEX: 187; LEFT: 416px; POSITION: absolute; TOP: 808px"
				tabIndex="35" runat="server" Text="תואר שני"></asp:checkbox><asp:checkbox id="chkDoctorate" style="Z-INDEX: 188; LEFT: 328px; POSITION: absolute; TOP: 808px"
				tabIndex="36" runat="server" Text="דוקטורט"></asp:checkbox><asp:label id="Label30" style="Z-INDEX: 189; LEFT: 632px; POSITION: absolute; TOP: 848px" runat="server"
				Width="127px">מצב משפחתי רצוי</asp:label><asp:checkbox id="chkSingle" style="Z-INDEX: 190; LEFT: 560px; POSITION: absolute; TOP: 848px"
				tabIndex="37" runat="server" Text="רווק"></asp:checkbox><asp:checkbox id="chkDevoursed" style="Z-INDEX: 191; LEFT: 432px; POSITION: absolute; TOP: 848px"
				tabIndex="39" runat="server" Text="גרוש"></asp:checkbox><asp:checkbox id="chkSeperated" style="Z-INDEX: 192; LEFT: 496px; POSITION: absolute; TOP: 848px"
				tabIndex="38" runat="server" Text="פרוד"></asp:checkbox><asp:checkbox id="chkWiddow" style="Z-INDEX: 193; LEFT: 368px; POSITION: absolute; TOP: 848px"
				tabIndex="40" runat="server" Text="אלמן"></asp:checkbox><asp:requiredfieldvalidator id="RequiredFieldValidator8" style="Z-INDEX: 194; LEFT: 632px; POSITION: absolute; TOP: 656px"
				runat="server" ErrorMessage="?" ControlToValidate="txtOtherPersonDescription"></asp:requiredfieldvalidator></form>
	</body>
</HTML>
