package JavaCC;

/* Generated By:JavaCC: Do not edit this line. Token.java Version 3.0 */

import JavaCC.JavaParserConstants;

/**
 * Describes the input token stream.
 */

public class Token {
        public int kind;
        public int beginLine;
        public int beginColumn;
        public int endLine;
        public int endColumn;
        public String image;
        private static int ID=0;
        //anigno:
        //added public uniqueId for each token, default is -1, no ID
        public int uniqueID=-1;
        //anigno
        //anigno:
        //added SimpleNode connectedNode to hold the first node that discover this token
        public SimpleNode connectedNode=null;
        //anigno:
        public Token next;
        public Token specialToken;

        //anigno:
        //function to return uniqueID number for each token
        //usually called from JavaParserTokenManager.jjFillToken()
        public int getUniqueID (){
                return ID++;
        }//getUniqueID()

        public String toString()
        {
           return image;
        }
        public static final Token newToken(int ofKind)
        {
           switch(ofKind)
           {
             default : return new Token();
             case JavaParserConstants.RUNSIGNEDSHIFT:
             case JavaParserConstants.RSIGNEDSHIFT:
             case JavaParserConstants.GT:
             return new GTToken();
           }
        }

  public static class GTToken extends Token
  {
     int realKind = JavaParserConstants.GT;
  }
}
